### ISSUE TITLE
PHP 8.3 Bug: preg_match() Compilation failed (Invalid range in character class) in tce_functions_form.php

### ISSUE THREAD

**Issue by isnardo** [tecnickcom/tcexam#460]
Hello! I am running TCExam on an Ubuntu Pro server with PHP 8.3. When trying to create or edit a user from the admin panel, the system throws a Fatal Error regarding an invalid range in the regular expression for the email field.

In PHP 8.3, regular expression rules are stricter, and an unescaped or misplaced hyphen (-) in the middle of a character class causes a compilation error.
Location of the bug:
shared/code/tce_functions_form.php on line 63

Current code causing the error: 
define('K_EMAIL_RE_PATTERN', '^([a-zA-Z0-9_\.\-\+\%]+)@([a-zA-Z0-9\.\-]+)$');

Proposed Fix:
Move the hyphen to the end of the character class group:
define('K_EMAIL_RE_PATTERN', '^([a-zA-Z0-9_\.\+\%\-]+)@([a-zA-Z0-9\.\-]+)$');

Applying this fix completely resolves the issue on PHP 8.3. 
Hope this helps to patch it in the next commit!

**Comment by darekpisz** [comment]
You have a new clean install of TCExam. Does the **User Selection** page (admin/code/tce_select_users.php) sort users by clicking: user, surname, name, registration date?

Your fix works.
The email address can be changed. The address is saved, but the file:
/admin/code/tce_edit_user.php
does not work properly.
It also clears the group to which the user is assigned.
The result is that the user cannot see the tests after logging in.

Edit:
Your fix also works on PHP 8.0...
Several people have already written that you can add the configuration file:
\shared\config\tce_config.php
from TCExam version 16.3.7 and everything works fine...

The problem is on a new clean install...
I've prepared some fixed files for version 16.6.3 so that you can use it without copying the configuration file from the older version of TCExam.

[tcexam-main_16.6.3_FIX.zip](https://github.com/user-attachments/files/28340735/tcexam-main_16.6.3_FIX.zip)

Files checked with PHP 8.0, PHP 8.3 and PHP 8.4 - work fine.

**Comment by nicolaasuni** [comment]
@isnardo Thanks for the report - confirmed and fixed. The K_EMAIL_RE_PATTERN character classes contained a hyphen mid-class that became an invalid range after stripslashes() in the form validator, which PCRE rejects on modern PHP. Fixed in v17.1.0. Closing as resolved.
